# Generated by Django 2.1 on 2018-09-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers_Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(db_column='Customer_ID', default=0)),
                ('customer_name', models.CharField(blank=True, db_column='Customer_Name', max_length=12, null=True)),
                ('customer_phone', models.CharField(blank=True, db_column='Customer_Phone', max_length=25, null=True)),
                ('customer_address', models.CharField(db_column='Customer_Address', default='', max_length=45)),
                ('customer_birthday', models.DateTimeField(blank=True, db_column='Customer_Birthday', null=True)),
                ('customer_occupation', models.CharField(blank=True, db_column='Customer_Occupation', max_length=12, null=True)),
                ('customer_gender', models.CharField(blank=True, db_column='Customer_Gender', max_length=5, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='customers_rental',
            unique_together={('customer_id', 'customer_address')},
        ),
    ]
