# Generated by Django 2.1 on 2018-09-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='employee_id',
            field=models.IntegerField(blank=True, default=0, max_length=20, null=True),
        ),
    ]
