# Generated by Django 2.1 on 2018-09-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180919_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Employee', 'Employee'), ('Employee', 'Manager')], max_length=50),
        ),
    ]
