# Generated by Django 2.1 on 2018-10-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_userprofile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Employee', 'Employee'), ('Employee', 'Manager')], default='Customer', max_length=50),
        ),
    ]
